config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :projects do
  get 'budget', to: 'budget#index'
  post 'budget', to: 'budget#snapshot'

  get 'budget/snapshots', to: 'budget#history'
  get 'budget/snapshots/:id', to: 'budget#view_snapshot'
  get 'budget/snapshots/:from_id..:to_id', to: 'budget#compare_snapshots'
  get 'budget/snapshots/:from_id..', to: 'budget#compare_snapshots'
  get 'budget/schedule', to: 'budget#schedule'
  get 'budget/create_issues', to: 'budget#create_issues_preview'
  post 'budget/create_issues', to: 'budget#create_issues'

  get 'budget/categories', to: 'budget_categories#index'
  match 'budget/categories/bulk_add', to: 'budget_categories#bulk_add'
  match 'budget/categories/:action', controller: 'budget_categories'
  match 'budget/categories/:action/:id', controller: 'budget_categories'

  match 'budget/items/edit/:category_id', controller: 'budget_items', action: 'edit'
  match 'budget/items/:id', controller: 'budget_items', action: 'show'

  get 'cashflow', to: 'cashflow#report'
  get 'cashflow/list', to: 'cashflow#index'
  match 'cashflow/issues/:action', controller: 'cashflow_issues'
  match 'cashflow/issues/:action/:id', controller: 'cashflow_issues'

  match 'taxes', controller: 'tax_tables', action: 'index'
  match 'taxes/:action', controller: 'tax_tables'
  match 'taxes/:action/:id', controller: 'tax_tables'
  match 'cashflow_issues/update_form', :controller => 'cashflow_issues', :action => 'update_form', :via => [:put, :post], :as => 'cashflow_issue_form'
end

app/models/cashflow_issue.rb
class CashflowIssue < Issue
  def custom_field_values
    values = super

    # If we have the transaction_type Issue Custom Field with the value of "Income"
    transaction_type = values.find { |field| field.custom_field.label == "transaction_type"}

    # We should remove the budget_item
    if !transaction_type.nil? && ['Income', 'Receita'].include?(transaction_type.value())
      values.reject { |field| field.custom_field.label == "budget_item" }
    else
      values
    end
  end

end

app/controllers/cashflow_issues_controller.rb
# coding: utf-8
class CashflowIssuesController < CashflowController
  unloadable

  helper :custom_fields
  include CustomFieldsHelper
  before_filter :create_issue, only: [:new, :create, :update_form]
  before_filter :load_issue, only: [:edit, :update]

  def create
    # Redmine hook, let's call it instead of calling the original method
    call_hook(:controller_issues_new_before_save, { :params => params, :issue => @issue })

    if @issue.save
      # Redmine hook, let's call it instead of calling the original method
      call_hook(:controller_issues_new_after_save, { :params => params, :issue => @issue})

      respond_to do |format|
        format.html {
          flash[:notice] = l(:notice_issue_successful_create, :id => view_context.link_to("##{@issue.id}", issue_path(@issue), :title => @issue.subject))
          if params[:continue]
            attrs = {:parent_issue_id => @issue.parent_issue_id}.reject {|k,v| v.nil?}
            redirect_to project_new_cashflow_issue_path(@issue.project, :issue => attrs)
          else
            redirect_to project_cashflow_path
          end
        }
        format.api  { render :action => 'show', :status => :created, :location => issue_url(@issue) }
      end
      return
    else
      respond_to do |format|
        format.html { render :action => 'new' }
        format.api  { render_validation_errors(@issue) }
      end
    end
  end

  def update
    begin
      call_hook(:controller_issues_edit_before_save, { :params => params, :issue => @issue })
      @issue.save!
      call_hook(:controller_issues_edit_after_save, { :params => params, :issue => @issue})
      redirect_to action: 'index'
    rescue ActiveRecord::RecordInvalid
      edit
      render action: 'edit'
    end
  end

  protected

  def create_issue
    @issue = CashflowIssue.new
    fill_issue
  end

  def load_issue
    @issue = CashflowIssue.find(params[:id])
    fill_issue
  end

  def fill_issue
    @issue.project = @project
    @issue.tracker = @tracker

    @issue.author ||= User.current
    @issue.start_date ||= Date.today
    @issue.safe_attributes = params[:issue]

    @allowed_statuses = @issue.new_statuses_allowed_to(User.current)
  end

end

app/views/cashflow_issues/_form.html.erb
<%= labelled_fields_for :issue, @issue do |f| %>
  <%= call_hook(:view_issues_form_details_top, { :issue => @issue, :form => f }) %>

  <% if @issue.safe_attribute? 'subject' %>
    <p><%= f.text_field :subject, :size => 80, :maxlength => 255, :required => true %></p>
  <% end %>

  <% if @issue.safe_attribute? 'custom_field_values' %>
    <%= render :partial => 'cashflow_issues/form_custom_fields' %>
  <% end %>

  <% if @issue.safe_attribute?('status_id') && @allowed_statuses.present? %>
    <p><%= f.select :status_id, (@allowed_statuses.collect {|p| [p.name, p.id]}), {:required => true} %></p>

  <% else %>
    <p><label><%= l(:field_status) %></label> <%= h(@issue.status.name) %></p>
  <% end %>

<% end %>

app/views/cashflow_issues/_form_custom_fields.html.erb
<% custom_field_values = @issue.editable_custom_field_values %>
<% custom_field_values.each do |value| %>
  <p>
  <%= content_tag 'label', :for => "issue_custom_field_values_#{value.custom_field.id}"  do %>
    <span><%= I18n.t('cashflow_' + value.custom_field.label) %></span>
    <%= (@issue.required_attribute?(value.custom_field_id) || value.custom_field.is_required?) ? "<span class=\"required\">*</span>".html_safe : "" %>
  <% end %>

  <% options = value.custom_field.label == "transaction_type" ? { onchange: "updateIssueFrom('#{escape_javascript project_cashflow_issue_form_path(@project, :id => @issue, :format => 'js')}')" }  : {} %>

  <%= custom_field_tag_with_options :issue, value, options %>

  </p>
<% end -%>

app/views/cashflow_issues/edit.html.erb
<h2>
  <%= link_to I18n.t(:cashflow_title), action: :index, id: nil %>
  »
  <%= I18n.t('cashflow.edit_transaction') %>
</h2>

<%= call_hook(:view_issues_new_top, {:issue => @issue}) %>

<%= form_tag({ controller: :cashflow_issues, action: :update, id: @issue.id }, {id: 'issue-form', multipart: true}) do |f| %>
  <%= error_messages_for 'issue' %>

  <div class="box tabular">
    <div id="all_attributes">
    <%= render :partial => 'cashflow_issues/form', :locals => {:f => f} %>
    </div>
  </div>

  <%= submit_tag l(:button_save) %>
<% end %>

app/views/cashflow_issues/new.html.erb
<h2>
  <%= link_to I18n.t(:cashflow_title), action: :index %>
  »
  <%= I18n.t('cashflow.new_transaction') %>
</h2>

<%= call_hook(:view_issues_new_top, {:issue => @issue}) %>

<%= form_tag({ controller: :cashflow_issues, action: :create }, {id: 'issue-form', multipart: true}) do |f| %>
  <%= error_messages_for 'issue' %>

  <div class="box tabular">
    <div id="all_attributes">
    <%= render :partial => 'cashflow_issues/form', :locals => {:f => f} %>
    </div>
  </div>

  <%= submit_tag l(:button_create) %>
  <%= submit_tag l(:button_create_and_continue), :name => 'continue' %>
<% end %>

app/views/cashflow_issues/update_form.js.erb
replaceIssueFormWith('<%= escape_javascript(render :partial => 'form') %>');